### ISSUE TITLE
ALSO function not found

### ISSUE THREAD

**Issue by KatherineKing** [dannymorris/ALSO#1]
> devtools::install_github("dannymorris/ALSO")
Skipping install of 'ALSO' from a github remote, the SHA1 (016f6076) has not changed since last install.
  Use `force = TRUE` to force installation
> library(ALSO)
> lm_also <- ALSO(data = c2s_scaled, model_function = lm, cross_validate = F)
Error in ALSO(data = c2s_scaled, model_function = lm, cross_validate = F) : 
  could not find function "ALSO"
> devtools::install_github("dannymorris/ALSO", force=TRUE)
Downloading GitHub repo dannymorris/ALSO@master
from URL https://api.github.com/repos/dannymorris/ALSO/zipball/master
Installing ALSO
"C:/PROGRA~1/MIE74D~1/MLSERV~1/R_SERVER/bin/x64/R" --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  "C:/Users/20790311/AppData/Local/Temp/3/RtmpozZg1d/devtools292843b35840/dannymorris-ALSO-016f607"  \
  --library="C:/Users/20790311/Documents/R/win-library/3.4" --install-tests 

* installing *source* package 'ALSO' ...
Warning in as.POSIXlt.POSIXct(x, tz) :
  unable to identify current timezone 'C':
please set environment variable 'TZ'
** R
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (ALSO)
In R CMD INSTALL
Reloading installed ALSO
> library(ALSO)
> lm_also <- ALSO(data = c2s_scaled, model_function = lm, cross_validate = F)
Error in ALSO(data = c2s_scaled, model_function = lm, cross_validate = F) : 
  could not find function "ALSO"

**Comment by dannymorris** [comment]
@KatherineKing Please try `ALSO::ALSO_RF(data = c2s_scaled)`. The function `ALSO()` currently does not exist within the package. It has been replaced by `ALSO_RF()`, which by default implements a speedier Random Forest (via the *ranger* package) as the base learner.

In the near future, the `ALSO` function will likely return to give users an option to specify a different algorithm.
